name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: ['0.13.0']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}

    - name: Run tests
      run: zig build test

    - name: Build
      run: zig build -Doptimize=ReleaseFast

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: changelog-${{ matrix.os }}
        path: zig-out/bin/changelog*
